### PR TITLE
Added CSV icons and photoshop template

### PR DESCRIPTION
**Pull request by janslow**
Added CSV icons (16, 32, 48 and 512px) and a photoshop template for
adding text to the _blank icon

### CODE REVIEW

**Comment by AmitMY** [comment]
@micho Any chance of merging this old PR?

**Comment by micho** [comment]
Hi! I don't have access repo here... @saimonmoore can you merge it?

**Comment by AmitMY** [comment]
@micho Sorry, tagged you as you are the one with 87.5% commits for this repo :)
Btw, merge closes: https://github.com/teambox/Free-file-icons/issues/11

**Comment by micho** [comment]
Yeah, no worries! It's just that I don't work there anymore :)

Maybe @somebody32?

**Comment by AmitMY** [comment]
@somebody32 Thanks!

**Pull request merged**
